import { createAdminClient } from '../lib/supabase/admin';

async function main() {
    console.log('🌱 Starting database seed script...');
    const supabase = createAdminClient();

    // 1. DELETE EXISTING TEST DATA (Idempotency)
    console.log('🧹 Cleaning up old test users...');
    const { data: { users }, error: listError } = await supabase.auth.admin.listUsers();
    if (listError) {
        console.error('Failed to list users:', listError);
        process.exit(1);
    }

    const testUsers = users.filter(u => u.email?.endsWith('@test.fragswipe.local'));
    for (const user of testUsers) {
        const { error } = await supabase.auth.admin.deleteUser(user.id);
        if (error) {
            console.error(`Failed to delete user ${user.email}:`, error);
        } else {
            console.log(`✅ Deleted ${user.email}`);
        }
    }

    // 2. CREATE NEW USERS
    console.log('👥 Creating test users...');
    const usersToCreate = [
        { email: 'admin@test.fragswipe.local', password: 'password123', role: 'admin', tier: 'pro', full_name: 'Test Admin' },
        { email: 'seller@test.fragswipe.local', password: 'password123', role: 'store', tier: 'store', full_name: 'Test Seller' },
        { email: 'buyer@test.fragswipe.local', password: 'password123', role: 'member', tier: 'free', full_name: 'Test Buyer' },
    ];

    const createdUsers: Record<string, string> = {};

    for (const u of usersToCreate) {
        const { data, error } = await supabase.auth.admin.createUser({
            email: u.email,
            password: u.password,
            email_confirm: true,
        });

        if (error || !data.user) {
            console.error(`Failed to create ${u.email}:`, error);
            process.exit(1);
        }

        createdUsers[u.email] = data.user.id;
        console.log(`✅ Created ${u.email}`);

        // Insert Profile
        // We UPSERT in case a trigger already created the profile
        const { error: profileError } = await supabase.from('profiles').upsert({
            id: data.user.id,
            full_name: u.full_name,
            whatsapp_number: '+27820000000',
            raw_address: 'Cape Town, South Africa',
            neighbourhood: 'Cape Town CBD',
            location: 'POINT(18.4232 -33.9249)', // PostGIS format
            role: u.role,
            subscription_tier: u.tier,
        });

        if (profileError) {
            console.error(`Failed to create profile for ${u.email}:`, profileError);
            process.exit(1);
        }
    }

    // 3. CREATE LISTINGS FOR SELLER
    console.log('🛍️ Creating test listings...');
    const sellerId = createdUsers['seller@test.fragswipe.local'];
    const categories = ['coral_sps', 'coral_lps', 'coral_soft', 'zoanthid', 'anemone', 'fish', 'invert', 'macro_algae', 'hardscape', 'hardware'];

    const activeListings = [];
    for (let i = 0; i < 20; i++) {
        activeListings.push({
            seller_id: sellerId,
            title: `Test Listing ${i + 1}`,
            description: `This is test listing number ${i + 1} generated by the seed script.`,
            price: Math.floor(Math.random() * 900) + 100, // 100 to 999
            category: categories[i % categories.length],
            status: 'active',
            location: 'POINT(18.4232 -33.9249)',
            neighbourhood: 'Cape Town CBD',
            tags: ['test', 'seed'],
        });
    }

    const { error: activeError } = await supabase.from('listings').insert(activeListings);
    if (activeError) {
        console.error('Failed to create active listings:', activeError);
        process.exit(1);
    }
    console.log('✅ Created 20 active listings.');

    // 4. CREATE SHADOW BANNED LISTINGS
    const bannedListings = [];
    for (let i = 0; i < 5; i++) {
        bannedListings.push({
            seller_id: sellerId,
            title: `Banned Listing ${i + 1}`,
            description: `This listing has HTTP links inside like https://example.com which should have triggered shadow ban.`,
            price: 500,
            category: 'coral_sps',
            status: 'shadow_banned',
            location: 'POINT(18.4232 -33.9249)',
            neighbourhood: 'Cape Town CBD',
            tags: ['banned', 'test'],
        });
    }

    const { error: banError } = await supabase.from('listings').insert(bannedListings);
    if (banError) {
        console.error('Failed to create shadow banned listings:', banError);
        process.exit(1);
    }
    console.log('✅ Created 5 shadow-banned listings.');

    console.log('🎉 Seed script completed successfully!');
    process.exit(0);
}

main().catch(e => {
    console.error('Unexpected error:', e);
    process.exit(1);
});
